### ISSUE TITLE
Gulp needs to set the permissions for deployment 

### ISSUE THREAD

**Issue by butlerx** [redbrick/TechWeek#52]

**Comment by chakrihacker** [comment]
can you please describe

**Comment by butlerx** [comment]
when gulp is run it needs to make sure the dist, 2015 and 2016 folder have their permission set to 755 and all their children as well as events.json and index.html have permission of 644 644

**Comment by rcass** [comment]
Has any one taken up this issue @butlerx ?  I would like to take a look at it if it has no been resolved yet

**Comment by butlerx** [comment]
nope go ahead

**Comment by rcass** [comment]
Awesome! I will take a look at this now and let you know how it goes.

**Comment by butlerx** [comment]
no longer seems to be an issue
