### ISSUE TITLE
Firefox issue

### ISSUE THREAD

**Issue by zergless** [redbrick/TechWeek#70]
![selection_009](https://cloud.githubusercontent.com/assets/3275788/23801574/85406034-05a8-11e7-9d61-2a4fb48a6c6d.png)
Firefox doesn't render this correctly on http://techweek.dcu.ie/CFT/

**Comment by VoyTechnology** [comment]
I presume you mean spacing on the left and right correct?

**Comment by zergless** [comment]
Look at the words on the first few lines
